version: 1
builder:
  configs:
    - platform: ios
      scheme: swiftui-text-builder
    - platform: macos-spm
      scheme: swiftui-text-builder
    - platform: tvos
      scheme: swiftui-text-builder
    - platform: visionos
      scheme: swiftui-text-builder
    - platform: watchos
      scheme: swiftui-text-builder
    - documentation_targets: [TextBuilder]
