name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: '3 3 * * 2'  # 3:03 AM, every Tuesday

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  macOS:
    name: ${{ matrix.platform }} (Swift ${{ matrix.swift }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-12
        platform:
          - iOS
          - macOS
          - tvOS
          - watchOS
        swift:
          - 5.6
          - 5.7
    steps:
    - uses: actions/checkout@v2
    - name: Install additional SDKs
      if: ${{ matrix.swift == 5.7 && (matrix.platform == 'tvOS' || matrix.platform == 'watchOS') }}
      run: xcodebuild -downloadAllPlatforms
      env:
        DEVELOPER_DIR: /Applications/Xcode_14.0.app/Contents/Developer
    - uses: mxcl/xcodebuild@v1
      with:
        platform: ${{ matrix.platform }}
        swift: ~${{ matrix.swift }}
        scheme: TextBuilder
