name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: "3 3 * * 2" # 3:03 AM, every Tuesday

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macOS:
    if: github.event_name != 'pull_request' || !contains(github.event.pull_request.title, '[skip ci]')
    name: ${{ matrix.platform }} (Swift ${{ matrix.swift }})
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        platform:
          - iOS
          - mac-catalyst
          - macOS
          - tvOS
          - visionOS
          - watchOS
        swift:
          - "6.0"
          - "6.1"
          - "6.2"
    steps:
      - name: Git Checkout
        uses: actions/checkout@v5

      - name: Select Xcode version
        uses: mxcl/xcodebuild@v3
        with:
          swift: ~${{ matrix.swift }}
          action: none
          verbosity: xcbeautify

      - if: matrix.platform != 'mac-catalyst' && matrix.platform != 'macOS'
        name: Download Required Runtime
        run: xcodebuild -downloadPlatform ${{ matrix.platform }}

      - if: matrix.platform != 'mac-catalyst' && matrix.platform != 'macOS'
        name: List Available Simulators
        run: xcrun simctl list devices

      - name: Run Tests
        uses: mxcl/xcodebuild@v3
        with:
          swift: ~${{ matrix.swift }}
          platform: ${{ matrix.platform }}
          action: test
          verbosity: xcbeautify
