name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: '3 3 * * 2'  # 3:03 AM, every Tuesday

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macOS:
    name: ${{ matrix.platform }} (Swift ${{ matrix.swift }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - iOS
          - macOS
          - tvOS
          - watchOS
        swift:
          - 5.7
          - 5.8
          - 5.9
        include:
          - swift: 5.7
            os: macos-13
          - swift: 5.8
            os: macos-13
          - swift: 5.9
            os: macos-13
          - action: test
          - platform: tvOS
            action: build
          - platform: watchOS
            action: build
    steps:
    - uses: actions/checkout@v4
    - uses: mxcl/xcodebuild@v2
      with:
        action: ${{ matrix.action }}
        platform: ${{ matrix.platform }}
        swift: ~${{ matrix.swift }}
        scheme: TextBuilder
